name: 'Helm Deploy to Kubernetes'
description: 'Deploy Helm chart from OCI registry to Kubernetes cluster'
author: 'Simplify9'

inputs:
  chart-name:
    description: 'Name of the Helm chart'
    required: true
  chart-version:
    description: 'Version of the Helm chart to deploy'
    required: true
  registry:
    description: 'OCI registry URL where the chart is stored'
    required: false
    default: 'docker.io'
  repository:
    description: 'Repository path in the registry'
    required: true
  registry-username:
    description: 'Registry username for authentication'
    required: true
  registry-password:
    description: 'Registry password or token for authentication'
    required: true
  kubeconfig:
    description: 'Base64 encoded kubeconfig for cluster access'
    required: true
  release-name:
    description: 'Helm release name'
    required: false
    default: 'app'
  namespace:
    description: 'Kubernetes namespace to deploy to'
    required: false
    default: 'default'
  image-repository:
    description: 'Docker image repository (for --set image.repository)'
    required: false
  image-tag:
    description: 'Docker image tag (for --set image.tag)'
    required: false
  values-file:
    description: 'Path to values file (relative to chart)'
    required: false
  values:
    description: 'Additional Helm values as YAML string'
    required: false
  set-values:
    description: 'Additional --set values (comma-separated: key1=value1,key2=value2)'
    required: false
  set-string-values:
    description: 'Additional --set-string values (comma-separated: key1=value1,key2=value2)'
    required: false
  timeout:
    description: 'Helm deployment timeout'
    required: false
    default: '10m'
  wait:
    description: 'Wait for deployment to complete'
    required: false
    default: 'true'
  create-namespace:
    description: 'Create namespace if it does not exist'
    required: false
    default: 'true'
  helm-version:
    description: 'Helm version to install'
    required: false
    default: 'latest'
  kubectl-version:
    description: 'kubectl version to install'
    required: false
    default: 'latest'

outputs:
  release-status:
    description: 'Status of the Helm release'
    value: ${{ steps.deploy.outputs.status }}
  chart-url:
    description: 'Full OCI URL of the deployed chart'
    value: ${{ steps.deploy.outputs.chart-url }}
  namespace:
    description: 'Namespace where the release was deployed'
    value: ${{ inputs.namespace }}

runs:
  using: 'composite'
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: ${{ inputs.helm-version }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: ${{ inputs.kubectl-version }}

    - name: Configure Kubernetes context
      shell: bash
      run: |
        echo "Configuring Kubernetes context..."
        mkdir -p ~/.kube
        echo "${{ inputs.kubeconfig }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config
        
        echo "Current context:"
        kubectl config current-context
        
        echo "Cluster info:"
        kubectl cluster-info

    - name: Create namespace
      if: inputs.create-namespace == 'true'
      shell: bash
      run: |
        echo "Creating namespace: ${{ inputs.namespace }}"
        kubectl create namespace ${{ inputs.namespace }} --dry-run=client -o yaml | kubectl apply -f -

    # - name: Configure Helm registry authentication
    #   shell: bash
    #   run: |
    #     set -euo pipefail
    #     REG="${{ inputs.registry }}"
    #     # Normalize Docker Hub for Helm OCI
    #     if [ "$REG" = "docker.io" ] || [ "$REG" = "index.docker.io" ]; then
    #       REG="registry-1.docker.io"
    #     fi

    #     echo "Configuring Helm registry authentication for $REG"

    #     echo "${{ inputs.registry-password }}" | helm registry login "$REG" \
    #       -u "${{ inputs.registry-username }}" \
    #       --password-stdin


    - name: Prepare values file
      if: inputs.values != ''
      shell: bash
      run: |
        echo "Creating temporary values file..."
        cat > /tmp/custom-values.yaml << 'EOF'
        ${{ inputs.values }}
        EOF
        echo "Custom values:"
        cat /tmp/custom-values.yaml

    - name: Deploy Helm chart
      id: deploy
      shell: bash
      run: |
        # Construct chart URL
        # Allow user to pass a full chart reference (http(s):// or oci:// or a .tgz URL)
        # If chart-name already looks like a full reference, use it verbatim and ignore other pieces.
        if [[ "${{ inputs.chart-name }}" =~ ^https?:// ]] || [[ "${{ inputs.chart-name }}" =~ ^oci:// ]] || [[ "${{ inputs.chart-name }}" == *.tgz ]]; then
          CHART_URL="${{ inputs.chart-name }}"
          echo "Detected explicit chart reference, using as-is: $CHART_URL"
        else
          # Existing OCI construction logic
          if [ "${{ inputs.registry }}" != "docker.io" ]; then
            CHART_URL="oci://${{ inputs.registry }}/${{ inputs.repository }}/${{ inputs.chart-name }}:${{ inputs.chart-version }}"
          else
            CHART_URL="oci://${{ inputs.repository }}/${{ inputs.chart-name }}:${{ inputs.chart-version }}"
          fi
        fi
        
        echo "chart-url=${CHART_URL}" >> $GITHUB_OUTPUT
        
        echo "Deploying Helm chart..."
        echo "Chart URL: ${CHART_URL}"
        echo "Release name: ${{ inputs.release-name }}"
        echo "Namespace: ${{ inputs.namespace }}"
        
        # Debug: Show what we received
        echo "=== ACTION DEBUG: Received Values ==="
        echo "set-values input: '${{ inputs.set-values }}'"
        echo "set-string-values input: '${{ inputs.set-string-values }}'"
        echo "SECRET_VALUES env: '$SECRET_VALUES'"
        echo "SECRET_VALUES length: ${#SECRET_VALUES}"
        if [ -n "$SECRET_VALUES" ]; then
          echo "SECRET_VALUES hex dump:"
          echo "$SECRET_VALUES" | hexdump -C | head -5
          echo "Contains semicolons: $(echo "$SECRET_VALUES" | grep -c ';' || echo '0')"
          echo "Contains equals: $(echo "$SECRET_VALUES" | grep -c '=' || echo '0')"
          echo "Contains spaces: $(echo "$SECRET_VALUES" | grep -c ' ' || echo '0')"
        fi
        echo "======================================"
        
        # Build helm command as array to properly handle arguments with spaces and special characters
        HELM_ARGS=("helm" "upgrade" "--install" "${{ inputs.release-name }}" "${CHART_URL}" "--namespace" "${{ inputs.namespace }}")
        
        # Add timeout and wait options
        if [ "${{ inputs.wait }}" == "true" ]; then
          HELM_ARGS+=("--wait")
        fi
        HELM_ARGS+=("--timeout" "${{ inputs.timeout }}")
        
        # Add image repository and tag if provided
        if [ -n "${{ inputs.image-repository }}" ]; then
          HELM_ARGS+=("--set" "image.repository=${{ inputs.image-repository }}")
        fi
        if [ -n "${{ inputs.image-tag }}" ]; then
          HELM_ARGS+=("--set" "image.tag=${{ inputs.image-tag }}")
        fi
        
        # Add values file if provided
        if [ -n "${{ inputs.values-file }}" ]; then
          HELM_ARGS+=("--values" "${{ inputs.values-file }}")
        fi
        if [ "${{ inputs.values }}" != "" ]; then
          HELM_ARGS+=("--values" "/tmp/custom-values.yaml")
        fi
        
        # Add custom set values (regular values)
        if [ -n "${{ inputs.set-values }}" ]; then
          IFS=',' read -ra VALUES <<< "${{ inputs.set-values }}"
          for value in "${VALUES[@]}"; do
            HELM_ARGS+=("--set" "${value}")
          done
        fi
        
        # Add custom set-string values (secret values)
        # First try the environment variable (preferred), then fall back to input parameter
        secret_values=""
        if [ -n "$SECRET_VALUES" ]; then
          secret_values="$SECRET_VALUES"
          echo "Using secret values from environment variable"
        elif [ -n "${{ inputs.set-string-values }}" ]; then
          secret_values="${{ inputs.set-string-values }}"
          echo "Using secret values from input parameter"
        fi
        
        if [ -n "$secret_values" ]; then
          echo "Processing secret values..."
          echo "=== SECRET PROCESSING DEBUG ==="
          echo "secret_values variable: '$secret_values'"
          echo "secret_values length: ${#secret_values}"
          echo "============================="
          
          # Only process if we have actual content (not just whitespace)
          if [ -n "$(echo "$secret_values" | tr -d '[:space:]')" ]; then
            while [[ "$secret_values" == *","* ]]; do
              value="${secret_values%%,*}"
              if [ -n "$value" ]; then
                echo "Adding --set-string: $value"
                HELM_ARGS+=("--set-string" "$value")
              fi
              secret_values="${secret_values#*,}"
            done
            # Handle the last value (or only value if no commas)
            if [ -n "$secret_values" ]; then
              echo "Adding --set-string: $secret_values"
              HELM_ARGS+=("--set-string" "$secret_values")
            fi
          else
            echo "No secret values to process"
          fi
        else
          echo "No secret values provided"
        fi
        
        echo "Executing: ${HELM_ARGS[*]}"
        "${HELM_ARGS[@]}"
        
        echo "status=deployed" >> $GITHUB_OUTPUT

    - name: Verify deployment
      shell: bash
      run: |
        echo "Verifying deployment..."
        
        echo "Helm release status:"
        helm status ${{ inputs.release-name }} --namespace ${{ inputs.namespace }}
        
        echo "Checking pods in namespace ${{ inputs.namespace }}:"
        kubectl get pods -n ${{ inputs.namespace }} -l app.kubernetes.io/instance=${{ inputs.release-name }}
        
        echo "Checking services:"
        kubectl get services -n ${{ inputs.namespace }} -l app.kubernetes.io/instance=${{ inputs.release-name }}
        
        echo "Deployment verification completed!"

    - name: Output deployment information
      shell: bash
      run: |
        echo "### 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Release:** ${{ inputs.release-name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Namespace:** ${{ inputs.namespace }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Chart:** ${{ inputs.chart-name }}:${{ inputs.chart-version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Registry:** ${{ inputs.registry }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Repository:** ${{ inputs.repository }}" >> $GITHUB_STEP_SUMMARY
        if [ -n "${{ inputs.image-repository }}" ] && [ -n "${{ inputs.image-tag }}" ]; then
          echo "- **Image:** ${{ inputs.image-repository }}:${{ inputs.image-tag }}" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Management Commands:**" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo "# Check status" >> $GITHUB_STEP_SUMMARY
        echo "helm status ${{ inputs.release-name }} -n ${{ inputs.namespace }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "# View pods" >> $GITHUB_STEP_SUMMARY
        echo "kubectl get pods -n ${{ inputs.namespace }} -l app.kubernetes.io/instance=${{ inputs.release-name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "# Rollback if needed" >> $GITHUB_STEP_SUMMARY
        echo "helm rollback ${{ inputs.release-name }} -n ${{ inputs.namespace }}" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY