name: Simplify9 iOS Provisioning Profile
description: Install an iOS provisioning profile for code signing.
author: simplify9
inputs:
  mobileprovision-base64:
    required: true
    description: Base64-encoded .mobileprovision file.
runs:
  using: composite
  steps:
    - name: Install provisioning profile
      shell: bash
      run: |
        set -euo pipefail
        if [[ -z "${{ inputs.mobileprovision-base64 }}" ]]; then
          echo "::error::Input 'mobileprovision-base64' is empty. Provide a base64-encoded .mobileprovision."
          exit 1
        fi
        mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
        if ! printf '%s' "${{ inputs.mobileprovision-base64 }}" | base64 --decode > "$RUNNER_TEMP/profile.mobileprovision"; then
          echo "::error::Failed to decode 'mobileprovision-base64'. Ensure it is valid base64."
          exit 1
        fi
        ls -l "$RUNNER_TEMP/profile.mobileprovision"
        wc -c "$RUNNER_TEMP/profile.mobileprovision"
        if [[ ! -s "$RUNNER_TEMP/profile.mobileprovision" ]]; then
          echo "::error::Decoded provisioning profile is empty."
          exit 1
        fi
        security cms -D -i "$RUNNER_TEMP/profile.mobileprovision" >/dev/null
        UUID=$(security cms -D -i "$RUNNER_TEMP/profile.mobileprovision" | /usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin)
        if [[ -z "$UUID" ]]; then
          echo "::error::Failed to extract UUID from provisioning profile."
          exit 1
        fi
        cp "$RUNNER_TEMP/profile.mobileprovision" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
