name: Simplify9 iOS Provisioning Profile
description: Install an iOS provisioning profile for code signing.
author: simplify9
inputs:
  mobileprovision-base64:
    required: true
    description: Base64-encoded .mobileprovision file.
runs:
  using: composite
  steps:
    - name: Install provisioning profile
      shell: bash
      run: |
        set -euo pipefail
        if [[ -z "${{ inputs.mobileprovision-base64 }}" ]]; then
          echo "::error::Input 'mobileprovision-base64' is empty. Provide a base64-encoded .mobileprovision."
          exit 1
        fi
        CLEAN_BASE64=$(printf '%s' "${{ inputs.mobileprovision-base64 }}" | tr -d '\r\n ')
        if [[ -z "$CLEAN_BASE64" ]]; then
          echo "::error::Input 'mobileprovision-base64' contained only whitespace/newlines."
          exit 1
        fi
        mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
        if ! printf '%s' "$CLEAN_BASE64" | base64 --decode > "$RUNNER_TEMP/profile.mobileprovision"; then
          echo "::error::Failed to decode 'mobileprovision-base64'. Ensure it is valid base64."
          exit 1
        fi
        ls -l "$RUNNER_TEMP/profile.mobileprovision"
        wc -c "$RUNNER_TEMP/profile.mobileprovision"
        if [[ ! -s "$RUNNER_TEMP/profile.mobileprovision" ]]; then
          echo "::error::Decoded provisioning profile is empty."
          exit 1
        fi
        if security cms -D -i "$RUNNER_TEMP/profile.mobileprovision" >/dev/null 2>&1; then
          UUID=$(security cms -D -i "$RUNNER_TEMP/profile.mobileprovision" | /usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin)
        else
          UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' "$RUNNER_TEMP/profile.mobileprovision" 2>/dev/null || true)
        fi
        if [[ -z "$UUID" ]]; then
          echo "::error::Failed to extract UUID. Ensure the input is a raw .mobileprovision file (CMS) or a plist with a UUID field."
          exit 1
        fi
        cp "$RUNNER_TEMP/profile.mobileprovision" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
