name: Simplify9 iOS Signing Certs
description: Import iOS signing certificate into a temporary keychain.
author: simplify9
inputs:
  p12-base64:
    required: true
    description: Base64-encoded .p12 signing certificate.
  p12-password:
    required: true
    description: Password for the .p12 certificate.
  keychain-password:
    required: false
    description: Password for the temporary keychain.
    default: temporary_password
runs:
  using: composite
  steps:
    - name: Import signing certificate
      shell: bash
      run: |
        set -euo pipefail
        KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain-db
        KEYCHAIN_PASSWORD="${{ inputs.keychain-password }}"

        security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
        security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

        echo "${{ inputs.p12-base64 }}" | base64 --decode > $RUNNER_TEMP/cert.p12
        security import $RUNNER_TEMP/cert.p12 -k "$KEYCHAIN_PATH" -P "${{ inputs.p12-password }}" -T /usr/bin/codesign
        security list-keychains -d user -s "$KEYCHAIN_PATH"
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
