name: 'Setup Next.js for Cloudflare Workers'
description: 'Configures Next.js project for Cloudflare Workers deployment'
author: 'Simplify9'

inputs:
  package-manager:
    description: 'Package manager to use (npm, yarn, pnpm)'
    required: false
    default: 'npm'

outputs:
  setup-status:
    description: 'Status of the setup process'
    value: ${{ steps.setup.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Install Wrangler CLI globally
      shell: bash
      run: |
        echo "📦 Installing Wrangler CLI for Workers deployment..."
        npm install -g wrangler
        echo "✅ Wrangler CLI installed successfully"

    - name: Verify Wrangler installation
      shell: bash
      run: |
        echo "🔍 Verifying Wrangler installation..."
        wrangler --version
        echo "✅ Wrangler is ready for use"

    - name: Setup Next.js for Workers
      shell: bash
      run: |
        echo "🔧 Configuring Next.js for Cloudflare Workers..."
        
        # We don't need any special packages for pure Workers deployment
        # Next.js will be built normally and we'll create a custom worker entry point
        echo "✅ Next.js Workers setup completed"

    - name: Validate Next.js configuration for Workers
      shell: bash
      id: setup
      run: |
        echo "🔧 Validating Next.js configuration for Cloudflare Workers..."
        
        # Check if next.config.js/mjs exists
        if [ -f "next.config.js" ] || [ -f "next.config.mjs" ] || [ -f "next.config.ts" ]; then
          echo "✅ Next.js config file found"
        else
          echo "⚠️ No Next.js config file found, creating basic configuration..."
          cat > next.config.js << 'EOF'
        /** @type {import('next').NextConfig} */
        const nextConfig = {
          experimental: {
            runtime: 'edge',
          },
          // Optimize for Cloudflare Workers
          swcMinify: true,
          output: 'standalone',
        }
        
        module.exports = nextConfig
        EOF
          echo "✅ Created basic next.config.js for Workers"
        fi
        
        # Check package.json for required scripts
        if ! grep -q '"build"' package.json; then
          echo "⚠️ No build script found in package.json"
        fi
        
        echo "status=success" >> $GITHUB_OUTPUT
        echo "✅ Next.js setup for Workers completed successfully"

    - name: Display setup summary
      shell: bash
      run: |
        echo "## 🔧 Next.js Workers Setup Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Package Manager**: ${{ inputs.package-manager }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Deployment Type**: Pure Cloudflare Workers" >> $GITHUB_STEP_SUMMARY
        echo "- **CLI Tool**: Wrangler (installed globally)" >> $GITHUB_STEP_SUMMARY
        echo "- **Configuration**: Pure Workers deployment (not Pages)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📋 Next Steps" >> $GITHUB_STEP_SUMMARY
        echo "- Build your Next.js application" >> $GITHUB_STEP_SUMMARY
        echo "- Configure Wrangler for deployment" >> $GITHUB_STEP_SUMMARY
        echo "- Deploy to Cloudflare Workers" >> $GITHUB_STEP_SUMMARY