name: Build Docker Image via Reusable Workflow

on:
  push:
    branches: ["staging"]
  workflow_dispatch:
    inputs:
      app_name:
        description: "App name (image name)"
        required: true
        default: your-app
      version:
        description: "Version tag"
        required: true
        default: staging
      registry_profile:
        description: "Registry profile (s9, wisewell, etc.)"
        required: true
        default: s9
      docker_registry:
        description: "Default Docker registry base"
        required: true
        default: registry.digitalocean.com/sf9cr
      docker_registry_wisewell:
        description: "Wisewell registry base (optional)"
        required: false
      build_context:
        description: "Docker build context"
        required: true
        default: .
      dockerfile:
        description: "Dockerfile path"
        required: true
        default: Dockerfile

jobs:
  build-deploy:
    uses: simplify9/.github/.github/workflows/build-deploy-reusable.yml@main
    with:
      app_name: ${{ github.event.inputs.app_name || 'your-app' }}
      version: ${{ github.event.inputs.version || 'staging' }}
      docker_registry: ${{ github.event.inputs.docker_registry || 'registry.digitalocean.com/sf9cr' }}
      # Choose registry profile: 's9' (default) or 'wisewell' (or any new client matching your secrets naming)
      registry_profile: ${{ github.event.inputs.registry_profile || 's9' }}
      # Optional: when using profile 'wisewell', set the registry base here
      docker_registry_wisewell: ${{ github.event.inputs.docker_registry_wisewell }}
      build_context: ${{ github.event.inputs.build_context || '.' }}
      dockerfile: ${{ github.event.inputs.dockerfile || 'Dockerfile' }}
    secrets:
      # Default (s9) credentials
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_token: ${{ secrets.REGISTRY_TOKEN }}
      # Optional credentials for the 'wisewell' (or other) profile
      # WISEWELL_REGISTRY_USERNAME: ${{ secrets.WISEWELL_REGISTRY_USERNAME }}
      # WISEWELL_REGISTRY_TOKEN: ${{ secrets.WISEWELL_REGISTRY_TOKEN }}
      # ACME_REGISTRY_USERNAME: ${{ secrets.ACME_REGISTRY_USERNAME }}
      # ACME_REGISTRY_TOKEN: ${{ secrets.ACME_REGISTRY_TOKEN }}
