name: Simplify9 Xcode Build
description: Build and archive an iOS app using xcodebuild.
author: simplify9

inputs:
  workspace:
    required: true
    description: Path to the Xcode workspace (.xcworkspace).
  scheme:
    required: true
    description: Xcode scheme to build.
  configuration:
    required: true
    description: Build configuration (e.g., Release).
  archivePath:
    required: true
    description: Output path for the generated .xcarchive.
  destination:
    required: false
    description: Xcode destination (e.g., generic/platform=iOS).
    default: generic/platform=iOS

  # Signing controls
  signingStyle:
    required: false
    description: "manual or automatic"
    default: manual
  developmentTeam:
    required: false
    description: Apple Developer Team ID (e.g., ABCDE12345). Required for manual signing.
  provisioningProfileSpecifier:
    required: false
    description: Provisioning profile NAME (PROVISIONING_PROFILE_SPECIFIER) for manual signing.
  codeSignIdentity:
    required: false
    description: Code signing identity (CODE_SIGN_IDENTITY) for manual signing.
  bundleId:
    required: false
    description: Bundle identifier override (PRODUCT_BUNDLE_IDENTIFIER), optional.

runs:
  using: composite
  steps:
    - name: Build and archive
      shell: bash
      run: |
        set -euo pipefail

        # Base args
        ARGS=(
          -workspace "${{ inputs.workspace }}"
          -scheme "${{ inputs.scheme }}"
          -configuration "${{ inputs.configuration }}"
          -sdk iphoneos
          -destination "${{ inputs.destination }}"
          -archivePath "${{ inputs.archivePath }}"
          clean archive
          -verbose -showBuildTimingSummary
        )

        if [[ "${{ inputs.signingStyle }}" == "automatic" ]]; then
          # Automatic signing requires Apple account / API auth; keep it opt-in only
          ARGS+=(-allowProvisioningUpdates)
        else
          # Manual signing (CI-stable; no Accounts needed)
          if [[ -z "${{ inputs.developmentTeam }}" ]]; then
            echo "ERROR: inputs.developmentTeam is required for manual signing"
            exit 1
          fi
          if [[ -z "${{ inputs.provisioningProfileSpecifier }}" ]]; then
            echo "ERROR: inputs.provisioningProfileSpecifier is required for manual signing"
            exit 1
          fi

          ARGS+=(
            CODE_SIGN_STYLE=Manual
            DEVELOPMENT_TEAM="${{ inputs.developmentTeam }}"
            PROVISIONING_PROFILE_SPECIFIER="${{ inputs.provisioningProfileSpecifier }}"
          )

          if [[ -n "${{ inputs.bundleId }}" ]]; then
            ARGS+=(PRODUCT_BUNDLE_IDENTIFIER="${{ inputs.bundleId }}")
          fi

          if [[ -n "${{ inputs.codeSignIdentity }}" ]]; then
            ARGS+=(CODE_SIGN_IDENTITY="${{ inputs.codeSignIdentity }}")
          fi
        fi

        echo "Running: xcodebuild ${ARGS[*]}"
        xcodebuild "${ARGS[@]}"
