name: Simplify9 Xcode Build
description: Build and archive an iOS app using xcodebuild.
author: simplify9

inputs:
  workspace:
    required: true
    description: Path to the Xcode workspace (.xcworkspace).
  scheme:
    required: true
    description: Xcode scheme to build.
  configuration:
    required: true
    description: Build configuration (e.g., Release).
  archivePath:
    required: true
    description: Output path for the generated .xcarchive.
  destination:
    required: false
    description: Xcode destination (e.g., generic/platform=iOS).
    default: generic/platform=iOS

  # Signing controls
  signingStyle:
    required: false
    description: "manual or automatic"
    default: manual

  developmentTeam:
    required: false
    description: Apple Developer Team ID (e.g., ABCDE12345). Required for manual signing.

  # Prefer UUID if you have it (most deterministic)
  provisioningProfileUuid:
    required: false
    description: Provisioning profile UUID (PROVISIONING_PROFILE) for manual signing.

  # Otherwise, profile name works too
  provisioningProfileSpecifier:
    required: false
    description: Provisioning profile NAME (PROVISIONING_PROFILE_SPECIFIER) for manual signing.

  codeSignIdentity:
    required: false
    description: Code signing identity (CODE_SIGN_IDENTITY), e.g. "Apple Distribution" or "Apple Development".

  bundleId:
    required: false
    description: Bundle identifier override (PRODUCT_BUNDLE_IDENTIFIER), optional.

  keychainPath:
    required: false
    description: Path to the keychain that contains the signing identity (e.g. $RUNNER_TEMP/build.keychain-db). Strongly recommended in CI.

runs:
  using: composite
  steps:
    - name: Build and archive
      shell: bash
      run: |
        set -euo pipefail

        ARGS=(
          -workspace "${{ inputs.workspace }}"
          -scheme "${{ inputs.scheme }}"
          -configuration "${{ inputs.configuration }}"
          -sdk iphoneos
          -destination "${{ inputs.destination }}"
          -archivePath "${{ inputs.archivePath }}"
          clean archive
          -verbose -showBuildTimingSummary
        )

        if [[ "${{ inputs.signingStyle }}" == "automatic" ]]; then
          ARGS+=(-allowProvisioningUpdates)
        else
          # Manual signing
          if [[ -z "${{ inputs.developmentTeam }}" ]]; then
            echo "ERROR: inputs.developmentTeam is required for manual signing"
            exit 1
          fi

          # Require either UUID or Specifier
          if [[ -z "${{ inputs.provisioningProfileUuid }}" && -z "${{ inputs.provisioningProfileSpecifier }}" ]]; then
            echo "ERROR: Provide either inputs.provisioningProfileUuid or inputs.provisioningProfileSpecifier for manual signing"
            exit 1
          fi

          ARGS+=(
            CODE_SIGN_STYLE=Manual
            DEVELOPMENT_TEAM="${{ inputs.developmentTeam }}"
          )

          # If you have a UUID, prefer it
          if [[ -n "${{ inputs.provisioningProfileUuid }}" ]]; then
            ARGS+=(PROVISIONING_PROFILE="${{ inputs.provisioningProfileUuid }}")
          fi

          # Also allow specifier (name). Some setups need it for embedded targets.
          if [[ -n "${{ inputs.provisioningProfileSpecifier }}" ]]; then
            ARGS+=(PROVISIONING_PROFILE_SPECIFIER="${{ inputs.provisioningProfileSpecifier }}")
          fi

          if [[ -n "${{ inputs.bundleId }}" ]]; then
            ARGS+=(PRODUCT_BUNDLE_IDENTIFIER="${{ inputs.bundleId }}")
          fi

          if [[ -n "${{ inputs.codeSignIdentity }}" ]]; then
            ARGS+=(CODE_SIGN_IDENTITY="${{ inputs.codeSignIdentity }}")
          fi

          # CRITICAL for CI: tell codesign which keychain to use
          if [[ -n "${{ inputs.keychainPath }}" ]]; then
            ARGS+=(OTHER_CODE_SIGN_FLAGS="--keychain ${{ inputs.keychainPath }}")
          fi

          # Optional: reduce weirdness when Xcode tries to be smart
          ARGS+=(CODE_SIGNING_ALLOWED=YES CODE_SIGNING_REQUIRED=YES)
        fi

        echo "Running: xcodebuild ${ARGS[*]}"
        xcodebuild "${ARGS[@]}"
