name: 'Build Next.js for Cloudflare Workers'
description: 'Builds Next.js application and prepares it for Cloudflare Workers deployment'
author: 'Simplify9'

inputs:
  build-command:
    description: 'Build command to run'
    required: false
    default: 'npm run build'
  
  environment:
    description: 'Environment for build (sets NODE_ENV and ENVIRONMENT)'
    required: false
    default: 'production'
  
  cloudflare-build-command:
    description: 'Cloudflare Workers build command'
    required: false
    default: 'npx @cloudflare/next-on-pages'
  
  next-build-output:
    description: 'Next.js build output directory'
    required: false
    default: '.next'
  
  workers-output-dir:
    description: 'Workers output directory'
    required: false
    default: '.vercel/output/static'
  
  worker-script-path:
    description: 'Path to the worker script file'
    required: false
    default: '.vercel/output/static/_worker.js'
  
  assets-ignore-file:
    description: 'Path to assets ignore file'
    required: false
    default: '.vercel/output/static/.assetsignore'
  
  assets-ignore-content:
    description: 'Content for assets ignore file'
    required: false
    default: '_worker.js'

outputs:
  build-output:
    description: 'Path to build output directory'
    value: ${{ inputs.workers-output-dir }}
  
  worker-script:
    description: 'Path to worker script file'
    value: ${{ inputs.worker-script-path }}
  
  assets-ignore:
    description: 'Path to assets ignore file'
    value: ${{ inputs.assets-ignore-file }}

runs:
  using: 'composite'
  steps:
    - name: Build Next.js application
      shell: bash
      run: |
        echo "🏗️ Building Next.js application..."
        ${{ inputs.build-command }}
        echo "✅ Next.js build completed successfully"
      env:
        NODE_ENV: ${{ inputs.environment }}
        ENVIRONMENT: ${{ inputs.environment }}

    - name: Build for Cloudflare Workers
      shell: bash
      run: |
        echo "⚡ Converting Next.js build for Cloudflare Workers..."
        ${{ inputs.cloudflare-build-command }}
        echo "✅ Workers conversion completed successfully"

    - name: Create assets ignore file
      shell: bash
      run: |
        echo "📝 Creating assets ignore file..."
        
        # Create directory if it doesn't exist
        IGNORE_DIR=$(dirname "${{ inputs.assets-ignore-file }}")
        mkdir -p "$IGNORE_DIR"
        
        # Create assets ignore file
        echo "${{ inputs.assets-ignore-content }}" > "${{ inputs.assets-ignore-file }}"
        echo "✅ Assets ignore file created at ${{ inputs.assets-ignore-file }}"

    - name: Verify build output
      shell: bash
      run: |
        echo "🔍 Verifying build output..."
        
        if [ ! -d "${{ inputs.workers-output-dir }}" ]; then
          echo "❌ Build output directory not found: ${{ inputs.workers-output-dir }}"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi
        
        if [ ! -f "${{ inputs.worker-script-path }}" ]; then
          echo "❌ Worker file not found: ${{ inputs.worker-script-path }}"
          echo "Output directory contents:"
          ls -la "${{ inputs.workers-output-dir }}/"
          exit 1
        fi
        
        if [ ! -f "${{ inputs.assets-ignore-file }}" ]; then
          echo "❌ Assets ignore file not found: ${{ inputs.assets-ignore-file }}"
          exit 1
        fi
        
        echo "✅ Build verification completed successfully"
        echo ""
        echo "Build output summary:"
        echo "- Output directory: ${{ inputs.workers-output-dir }}"
        echo "- Worker file: ${{ inputs.worker-script-path }}"
        echo "- Assets ignore: ${{ inputs.assets-ignore-file }}"
        echo ""
        echo "Files in output directory:"
        ls -la "${{ inputs.workers-output-dir }}/" | head -10

    - name: Build summary
      shell: bash
      run: |
        echo "## 🏗️ Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Command**: ${{ inputs.build-command }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Output Directory**: .vercel/output/static/" >> $GITHUB_STEP_SUMMARY
        echo "- **Worker File**: ✅ _worker.js" >> $GITHUB_STEP_SUMMARY
        echo "- **Assets Ignore**: ✅ .assetsignore" >> $GITHUB_STEP_SUMMARY
        echo "- **Conversion Tool**: @cloudflare/next-on-pages" >> $GITHUB_STEP_SUMMARY