name: Call Minimal Secret Test

on:
  workflow_dispatch:

jobs:
  call-test:
    uses: ./.github/workflows/minimal-secret-test.yml
    with:
      test-input: 'test-value-${TEST_SECRET}'
    secrets:
      TEST_SECRET: 'my-secret-value'