name: Verify Secret Access

on:
  workflow_dispatch:

jobs:
  test-secret-access:
    runs-on: ubuntu-latest
    steps:
      - name: Test toJson(secrets) Content
        env:
          SECRETS_DEBUG: ${{ toJson(secrets) }}
        run: |
          echo "🔍 DEBUGGING: What's in toJson(secrets)?"
          echo "Available secrets keys:"
          echo "$SECRETS_DEBUG" | jq -r 'keys[]' || echo "Failed to parse as JSON"
          echo ""
          echo "Full secrets object (values hidden):"
          echo "$SECRETS_DEBUG" | jq 'with_entries(.value = "<hidden>")' || echo "Failed to parse as JSON"