name: Minimal Secret Test

on:
  workflow_call:
    inputs:
      test-input:
        required: true
        type: string
    secrets:
      TEST_SECRET:
        required: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Secret Access
        env:
          SECRETS_JSON: ${{ toJson(secrets) }}
          INPUT_VALUE: ${{ inputs.test-input }}
        run: |
          echo "🔍 DEBUGGING REUSABLE WORKFLOW SECRET ACCESS"
          echo "============================================"
          echo "Input received: $INPUT_VALUE"
          echo ""
          echo "Secrets JSON:"
          echo "$SECRETS_JSON"
          echo ""
          echo "Direct secret access:"
          echo "TEST_SECRET = ${{ secrets.TEST_SECRET }}"