name: Test Secret Access

on:
  workflow_dispatch:

jobs:
  test-known-secret:
    uses: ./.github/workflows/minimal-secret-test.yml
    with:
      test-input: 'Testing known secret access'
    secrets:
      TEST_SECRET: ${{ secrets.GITHUB_TOKEN }}
      
  test-org-secret:
    uses: ./.github/workflows/minimal-secret-test.yml
    with:
      test-input: 'Testing org secret access'
    secrets:
      TEST_SECRET: ${{ secrets.S9_GITHUB_TOKEN }}