name: Test Secret Substitution

on:
  workflow_dispatch:
    inputs:
      test_secret_value:
        description: 'Test secret value to use'
        required: false
        default: 'connect;string;userId=23fv'
        type: string

jobs:
  test-deploy:
    uses: simplify9/.github/.github/workflows/sw-cicd.yml@main
    with:
      chart-name: test-app
      major-version: '1'
      minor-version: '0'
      helm-set-values: |
        ingress.enabled=true,
        replicas=1,
        ingress.hosts={surl.sf9.io},
        environment="Staging",
        ingress.path="/api",
        ingress.tls[0].secretName="surl-tls",
        db="${DBCS_ESCAPED}"
      deploy-to-development: false
    secrets:
      DBCS_ESCAPED: ${{ inputs.test_secret_value }}
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
      
  # Just test the secret processing without full deployment
  test-secret-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Test Secret Substitution Logic
        env:
          SECRETS_JSON: '{"DBCS_ESCAPED":"connect;string;userId=23fv"}'
        run: |
          RAW_VALUES="ingress.enabled=true,replicas=1,ingress.hosts={surl.sf9.io},environment=\"Staging\",ingress.path=\"/api\",ingress.tls[0].secretName=\"surl-tls\",db=\"\${DBCS_ESCAPED}\""
          
          echo "🧪 Testing Secret Substitution"
          echo "==============================="
          echo "Original values: $RAW_VALUES"
          echo ""
          
          # Use Node.js to process the secret substitution (same logic as main workflow)
          PROCESSED_VALUES=$(node -e "
            const secrets = JSON.parse(process.env.SECRETS_JSON || '{}');
            const rawValues = process.argv[1] || '';
            
            const result = rawValues.replace(/\\\$\{([^}]+)\}/g, (match, secretName) => {
              if (secrets[secretName]) {
                const escapedValue = secrets[secretName].replace(/\"/g, '\\\\\"');
                return '\"' + escapedValue + '\"';
              }
              return match;
            });
            
            console.log(result);
          " "$RAW_VALUES")
          
          echo "Processed values: $PROCESSED_VALUES"
          echo ""
          echo "🚀 FINAL HELM COMMAND:"
          echo "====================="
          echo "helm upgrade --install test-app-dev oci://ghcr.io/simplify9/charts/test-app \\"
          echo "  --version 1.0.1 \\"
          echo "  --namespace development \\"
          echo "  --set $PROCESSED_VALUES \\"
          echo "  --timeout 10m"